POST https://node-test-nx4n.onrender.com/videos
Content-type: application/json

{
    "title": "video node",
    "description": "video novo",
    "duration": 100
}

###

GET https://node-test-nx4n.onrender.com/videos

###

PUT https://node-test-nx4n.onrender.com/videos/36de2298-d8b0-4f39-acf5-9b99c1c9284f
Content-type: application/json

{
    "title": "video completo",
    "description": "video novo",
    "duration": 100
}

###

DELETE https://node-test-nx4n.onrender.com/videos/e2d3a044-7a65-4b69-a14f-b830770f06ac
